### ISSUE TITLE
taxonomic_info not defined

### ISSUE THREAD

**Issue by igortru** [amillard/tax_myPHAGE#10]
command line:

 
 python taxmyphage run -i .50445598.fn -t 32
 
accession: OR776998.1

Classifying:   0%|                                                                                                                             | 0/1 [46:12<?, ?it/s]
Traceback (most recent call last):
  File "taxmyphage", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "tax_myPHAGE/taxmyphage/__main__.py", line 116, in main
    all_classification(
  File "tax_myPHAGE/taxmyphage/actions.py", line 175, in all_classification
    genome_taxo = classification(
                  ^^^^^^^^^^^^^^^
  File "tax_myPHAGE/taxmyphage/classify.py", line 820, in classification
    return taxonomic_info
           ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'taxonomic_info' where it is not associated with a value

**Comment by amillard** [comment]
thanks Igor. was the query a file with OR776998 in ?

**Comment by igortru** [comment]
yes

**Comment by rdenise** [comment]
Should be solve with the new released

Thank you for you help debugging the taxmyphage
