### ISSUE TITLE
findfont: Font family 'Arial' not found.

### ISSUE THREAD

**Issue by igortru** [amillard/tax_myPHAGE#11]
what I need to change remove this warning from output?

Classifying gi|2622989198|gb|OR786095.1| in result folder tax_myPHAGE/taxmyphage_results/Results_per_genome/gi_2622989198_gb_OR786095.1_...

Starting tax_my_phage analysis...

Number of phage genomes detected with mash distance of < 0.2 is:20

The mash distances obtained for this query phage
            is a minimum value of 0.0896287 and maximum value of 0.199716

Found 1 genera associated with this query genome

Only found 1 genus so will proceed with getting all genomes associated with that genus
Number of known species in the genus is 19 
 
It is not clear if the phage is a new species or not. Will run further analysis now to confirm this...

Will calculate and save heatmaps now                                                                                                                                                                  

findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.
findfont: Font family 'Arial' not found.

**Comment by rdenise** [comment]
Should be solve with the new released. We didn't properly configure the font

Thank you for you help debugging the taxmyphage
