### ISSUE TITLE
curious case : LC710660

### ISSUE THREAD

**Issue by igortru** [amillard/tax_myPHAGE#12]
according my analysis and first blastn hit it is Oslovirus 
but you classified it as Traversvirus  (same subfamily)

I would say, these legacy generas looks over-extended ,  both need to be split.

see blastn:

<img width="1852" alt="Screenshot 2024-01-16 at 7 31 06 PM" src="https://github.com/amillard/tax_myPHAGE/assets/5491864/d1dfdcc2-6cad-4baf-b356-c20beffc8229">
<img width="1669" alt="Screenshot 2024-01-16 at 7 34 55 PM" src="https://github.com/amillard/tax_myPHAGE/assets/5491864/98f52f8e-e4cd-42ad-a2f8-411c1bd7dfcc">

**Comment by rdenise** [comment]
Is taxmyphage gave the warning in the log/terminal about that it was not able to give an exact result because of this case?


> The number of expected genera based on current ICTV classification is different from the predicted number of genus clusters as predicted by VIRIDIC-algorithm. This does not mean the current ICTV classification is wrong (it might be) or that VIRIDIC-algorithm is wrong. It could be an edge  case that automated process cannot distinguish. It will require more manual curation to look at the output files)

**Comment by igortru** [comment]
results is ok, but output looks ugly.
How I can install arial font on unix?

**Comment by rdenise** [comment]
I think it is already installed I just did not put correctly how to call it in the script. I corrected that on the last commit that is not released yet.
