### ISSUE TITLE
[BUG] No output from taxmyphage similarity

### ISSUE THREAD

**Issue by DT1401** [amillard/tax_myPHAGE#13]
Using taxmyphage similarity for an all-vs-all analysis of a set of genomes creates an empty output folder.
No information is shown when using the --verbose flag.
The same behaviour is observed on both mamba and manual installs.

System: Ubuntu 22.04.3 LTS, 64 cores 256GB RAM

**Comment by rdenise** [comment]
Could you provide the command line and the fasta file you were using. It is weird that taxmyphage do not provide an output nor say anything

**Comment by rdenise** [comment]
Should be solve now with the new release, it will be available on pipy and conda soon

Thank you for your help discovering this bug
