### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sandraaran** [amillard/tax_myPHAGE#17]
**Describe the bug**
Error upgrading the new mash database

**To Reproduce**

1. Go to manual update for new VMR (https://github.com/amillard/tax_myPHAGE?tab=readme-ov-file#manual-update-for-new-vmr)
2. click in "New MASH database [here](https://https//millardlab-taxmyphage.s3.climb.ac.uk/ICTV_MSL39v1.msh)" text
3. a new screen with "can't access to this site" appear

**Expected behavior**

Download the new mash database

**Screenshots**
<img width="1080" alt="Captura de Pantalla 2024-08-19 a la(s) 21 48 27" src="https://github.com/user-attachments/assets/1bbae823-b5fb-4cbf-860b-2ae713e50cf5">

**Please complete the following information:**

***OS:*** 

 - [ ] Linux
 - [ ] Windows
 - [X] Mac

***taxmyPHAGE Version:***

0.3.0

**Additional context**
None

**Comment by amillard** [comment]
correct error in the link
