### ISSUE TITLE
[HELP] 

### ISSUE THREAD

**Issue by miryamcarrillo98** [amillard/tax_myPHAGE#18]
**Describe your problem**
I have installed taxmyphage but I get the same error each time I run it (attached screenshot). 

**To Reproduce**
conda activate taxmyphage

taxmyphage run -i name.fasta -t 4

**Screenshots / outputs**
![taxmyphage_error](https://github.com/user-attachments/assets/b2a06597-76e7-4907-ac64-a056cb940a4f)

**Please complete the following information):**

***OS:*** 

 - [ X] Linux
 - [ ] Windows
 - [ ] Mac

***taxmyPHAGE Version:***
 taxmyphage v0.3.1

**Comment by amillard** [comment]
ICTV have updated the VMR format . By default it will be pulling the latest file , which is now a different format 
go to 
 https://ictv.global/sites/default/files/VMR/VMR_MSL39_v1.xlsx
 put this file in the conda installation and rename it to VMR.xlsx 
 
We are working on a fix so the correct format is  installed
