### ISSUE TITLE
[BUG and ENHANCEMENT] Some bugs and enhancement suggestion

### ISSUE THREAD

**Issue by rdenise** [amillard/tax_myPHAGE#3]
Dear authors,

Here a list of some bug and enhancement I would suggest to implement.

### line 142: 

```python
df.sort_values('sim', ascending=False)
```

if you want to save the sorting, it should be either:

```python
df.sort_values('sim', ascending=False, inplace=True)
```

or 

```python
df = df.sort_values('sim', ascending=False)
```

---

### line 193

```python
font_size = min(fig_width, fig_height) * 0.9
```

I made a mistake when I calculate automatically the font size, a better way is like that

```python
font_size = (min(fig_width, fig_height) / max(df.shape[0], df.shape[1])) * 10
```

---

### In **line 117 to 119**

I don't understand the logic here.

```python
if (gA, gB) not in M and (gB, gB) not in M: continue
if (gA, gB) not in M: M[(gA, gB)] = M[(gB, gB)]
if (gB, gA) not in M: M[(gB, gA)] = M[(gA, gA)]
```

Mostly first you are looking if there is the comparison between gA and gB from the blast, which is logic. But the other part is looking if there is the comparison of the gB against itself, that doesn't really make sense because yes this thing should exist in a all vs all genomes comparison. And after the other test will create a big assumption that I don't understand as gA and gB are supposed to be different so why putting the comparison between gA against itself as the same comparison of gB agains gA and same would apply for gB against gA that should not be equal to gB against itself. This calculation will more than possibly create the fact that two genomes totally different will be consider as 100% identical at the end.

```python
if (gA, gB) not in M and (gB, gA) not in M: continue
if (gA, gB) not in M: M[(gA, gB)] = M[(gB, gA)]
if (gB, gA) not in M: M[(gB, gA)] = M[(gA, gB)]
```

---

### line 113

```python
genomes = list(set([x[0] for x in M.keys()] + [x[0] for x in M.keys()]))
```

it is weird that you concatenate twice the same list so I think it was intended to be:

```python
genomes = list(set([x[0] for x in M.keys()] + [x[1] for x in M.keys()]))
```

### Faster blastn result parsing

The calculation of the distance matrix from the blast output is really slow (taking 5 minutes for 421477 lines of blast results + the reading of the table by pandas).

at the moment the function is line 86 like this:

```python
def parse_blastn_file(self):
    ic("Reading", self.blastn_result_file)
    df = pd.read_table(self.blastn_result_file, names='qseqid sseqid pident length qlen slen mismatch nident gapopen qstart qend sstart send qseq sseq evalue bitscore'.split())
    self.blastn_df = df
    
    self.size_dict = dict(df['qseqid qlen'.split()].values) | dict(df['sseqid slen'.split()].values)

    # this part is slow ... filling the genome with all the matches
    M = {}
    for qseqid, sseqid, pident, length, qlen, slen, mismatch, nident, gapopen, qstart, qend, sstart, send, qseq, sseq, evalue, bitscore in tqdm(df.values):
        key = (qseqid, sseqid)
        if qstart > qend: qstart, qend = qend, qstart
        M.setdefault(key, [0]*qlen)
        v = M[key]
        gaps = 0
        for n, nt in enumerate(qseq):
            if nt == '-':
                gaps += 1
                continue
            if v[qstart-1+n-gaps] == 1: continue
            v[qstart-1+n-gaps] = int(sseq[n] == qseq[n])

    self.M = M
```

I found a way to reduce the time to 20 seconds using numpy and parsing the table directly to not have it in memory and so reduce the impact on memory as it seems to be no need to keep it in memory after getting the information inside

```python
def parse_blastn_file(self):
    ic("Reading", self.blastn_result_file)

    num_lines = rawgencount(self.blastn_result_file)

    self.size_dict = {}
    M = {}
    with gzip.open(self.blastn_result_file, 'rt') as df:
        for line in tqdm(df, total=num_lines):
            # do something with the line
            qseqid, sseqid, pident, length, qlen, slen, mismatch, nident, gapopen, qstart, qend, sstart, send, qseq, sseq, evalue, bitscore = line.rstrip().split()
            key = (qseqid, sseqid)
            M.setdefault(key, np.zeros(int(qlen)))

            if qseqid not in self.size_dict:
                self.size_dict[qseqid] = int(qlen) 
            if sseqid not in self.size_dict:
                self.size_dict[sseqid] = int(slen)

            # convert the strings to numpy arrays
            qseq = np.frombuffer(qseq.encode('utf-8'), dtype="S1")
            sseq = np.frombuffer(sseq.encode('utf-8'), dtype="S1")

            v = np.where(qseq == sseq, 1, 0)

            # find the indices of elements that are not equal to '-'. Here it is b'-' because the array is of type bytes.
            idx = qseq != b'-'

            # add the values to the matrix
            M[key][int(qstart)-1:int(qend)] += v[idx]

    # convert the matrix to a binary matrix
    M = {key:np.where(value != 0, 1, 0) for key, value in M.items()}

    self.M = M
```

it comes with two little function to quickly know the number of line in the file for tqdm progress bar

```python
def _make_gen(reader):
    """Generator to read a file piece by piece.
    Default chunk size: 1k.
    Args:
        reader (func): Function to read a piece of the file.
    Yields:
        generator: A generator object that yields pieces of the file.
    """
    b = reader(1024 * 1024)
    while b:
        yield b
        b = reader(1024*1024)

def rawgencount(filename):
    """Count the number of lines in a file.
    Args:
        filename (str): The name of the file to count.
    Returns:
        int: The number of lines in the file.
    """
    f = gzip.open(filename, 'rb') 
    f_gen = _make_gen(f.read)
    return sum( buf.count(b'\n') for buf in f_gen )
```

---

### Ordering the heatmap for a better visualisation

On the function heatmap line 147, it would be interesting to sort the matrix before plotting is to have a better visual representation of genome similar, next to each other. It can be done quickly by scipy linkage and dendrogram function.

it can be added line 160

```python
df = df.rename({'taxmyPhage':'query'}, axis=1).rename({'taxmyPhage':'query'}, axis=0)

# Make the matrix symmetric
df = df + df.T - np.diag(df.values.diagonal())

# Perform hierarchical clustering
Z = sch.linkage(df, method='ward')

# Plot the dendrogram
dendrogram = sch.dendrogram(Z, labels=df.index, no_plot=True)

# Looking for the query leave to put at the end
leaves_order = [leave for leave in dendrogram['ivl'] if leave != "query"] + ["query"]

# Here another method maybe slower
# leaves_order = []
# for leave in dendrogram['ivl']:
#     if "query" not in leave:
#         leaves_order.append(leave)
#     else:
#         query_leave = leave
# leaves_order.append(query_leave)

# Reorder the matrix
df = df.loc[leaves_order, leaves_order]
df.iloc[:,:] = np.triu(df.values, k=0)
# Maybe the following method is faster 
# df = df.where(np.triu(np.ones(df.shape)).astype(np.bool))

df.to_csv(matrix_out, sep='\t', index=True)
```

**Comment by rdenise** [comment]
For the function calculate_distances line 110, it takes 1 minutes at the moment to calculate the distance for the 116 genomes that correspond to the line of previous blastn results that have 421477:

```python
def calculate_distances(self):
    M = self.M
    size_dict = self.size_dict
    genomes = list(set([x[0] for x in M.keys()] + [x[0] for x in M.keys()]))
    # now calculating the distances
    L = []
    for gA, gB in combinations_with_replacement(genomes, 2):
        if (gA, gB) not in M and (gB, gB) not in M: continue
        if (gA, gB) not in M: M[(gA, gB)] = M[(gB, gB)]
        if (gB, gA) not in M: M[(gB, gA)] = M[(gA, gA)]
        
        
        idAB = sum(M[(gA, gB)])
        idBA = sum(M[(gB, gA)])
        lA = size_dict[gA]
        lB = size_dict[gB]
        simAB = ((idAB+idBA)*100)/(la+lB)
        distAB = 100-simAB

        aligned_fraction_genome_1 = idAB / la
        aligned_fraction_genome_2 = idBA / lB
        genome_length_ratio = lA / lB if lA < lB else lB / la
        L.append([gA, gB, distAB, aligned_fraction_genome_1, genome_length_ratio, aligned_fraction_genome_2])

    dfM = pd.DataFrame(L, columns='A B distAB afg1 glr afg2'.split())

    dfM['sim'] = 100 - dfM.distAB
    self.dfM = dfM
```

if you use matrix calculation instead of a loop it take now with my implementation 6.44 µs

```python
def calculate_distances(self):
    M = self.M
    size_dict = self.size_dict

    genome_arr = np.array(list(M.keys()))
    identity_arr = np.array(list(M.values()), dtype=object).reshape(-1, 1)
    dfM = pd.DataFrame(np.hstack([genome_arr, identity_arr]), columns=['A', 'B', 'identity_seq'])

    dfM["idAB"] = dfM['identity_seq'].apply(lambda x: np.sum(x))

    # creating a dictionary of genome name identity 
    # As the blast is double sided need to check the identity of both genomes by looking at the opposite pair
    dict_BA = dfM.set_index(["A", "B"]).idAB.to_dict()

    # Creating the pair of genomes in order B, A
    dfM["pair_BA"] = dfM.apply(lambda x: (x.A, x.B), axis=1)

    # Setting the identity of the pair B, A
    dfM["idBA"] = dfM.pair_BA.map(dict_BA)

    # If the identity of the pair B, A is NaN then the pair is A, B
    dfM.loc[dfM.idBA.isna(), "idBA"] = dfM.loc[dfM.idBA.isna(), "idAB"]

    # Map the size of the genome to the dataframe
    dfM["lA"] = dfM['A'].map(size_dict)
    dfM["lB"] = dfM['B'].map(size_dict)

    # Calculate the similarity
    dfM["simAB"] = ((dfM.idAB + dfM.idBA) * 100) / (dfM.lA + dfM.lB)

    # Calculate the distance
    dfM["distAB"] = 100 - dfM.simAB

    # Calculate the aligned fraction of the genome
    dfM["aligned_fraction_genome_1"] = dfM.idAB / dfM.lA
    dfM["aligned_fraction_genome_2"] = dfM.idBA / dfM.lB
    dfM["genome_length_ratio"] = dfM[["lA", "lB"]].min(axis=1) / dfM[["lA", "lB"]].max(axis=1)

    # Calculate the similarity
    dfM['sim'] = 100 - dfM.distAB

    # Remove the duplicate pairs
    dfM["ordered_pair"] = dfM.apply(lambda x: str(sorted(x.pair_BA)), axis=1)
    dfM = dfM.drop_duplicates("ordered_pair").reset_index(drop=True)

    # Remove the columns that are not needed
    dfM = dfM.drop(columns=['identity_seq', 'pair_BA', 'idAB', 'idBA', 'lA', 'lB', 'simAB'])

    self.dfM = dfM
```

**Comment by tsp-kucbd** [comment]
> For the function calculate_distances line 110, it takes 1 minutes at the moment to calculate the distance for the 116 genomes that correspond to the line of previous blastn results that have 421477:
> 
> ```python
> def calculate_distances(self):
>     M = self.M
>     size_dict = self.size_dict
>     genomes = list(set([x[0] for x in M.keys()] + [x[0] for x in M.keys()]))
>     # now calculating the distances
>     L = []
>     for gA, gB in combinations_with_replacement(genomes, 2):
>         if (gA, gB) not in M and (gB, gB) not in M: continue
>         if (gA, gB) not in M: M[(gA, gB)] = M[(gB, gB)]
>         if (gB, gA) not in M: M[(gB, gA)] = M[(gA, gA)]
>         
>         
>         idAB = sum(M[(gA, gB)])
>         idBA = sum(M[(gB, gA)])
>         lA = size_dict[gA]
>         lB = size_dict[gB]
>         simAB = ((idAB+idBA)*100)/(la+lB)
>         distAB = 100-simAB
> 
>         aligned_fraction_genome_1 = idAB / la
>         aligned_fraction_genome_2 = idBA / lB
>         genome_length_ratio = lA / lB if lA < lB else lB / la
>         L.append([gA, gB, distAB, aligned_fraction_genome_1, genome_length_ratio, aligned_fraction_genome_2])
> 
>     dfM = pd.DataFrame(L, columns='A B distAB afg1 glr afg2'.split())
> 
>     dfM['sim'] = 100 - dfM.distAB
>     self.dfM = dfM
> ```
> 
> if you use matrix calculation instead of a loop it take now with my implementation 6.44 µs
> 
> ```python
> def calculate_distances(self):
>     M = self.M
>     size_dict = self.size_dict
> 
>     genome_arr = np.array(list(M.keys()))
>     identity_arr = np.array(list(M.values()), dtype=object).reshape(-1, 1)
>     dfM = pd.DataFrame(np.hstack([genome_arr, identity_arr]), columns=['A', 'B', 'identity_seq'])
> 
>     dfM["idAB"] = dfM['identity_seq'].apply(lambda x: np.sum(x))
> 
>     # creating a dictionary of genome name identity 
>     # As the blast is double sided need to check the identity of both genomes by looking at the opposite pair
>     dict_BA = dfM.set_index(["A", "B"]).idAB.to_dict()
> 
>     # Creating the pair of genomes in order B, A
>     dfM["pair_BA"] = dfM.apply(lambda x: (x.A, x.B), axis=1)
> 
>     # Setting the identity of the pair B, A
>     dfM["idBA"] = dfM.pair_BA.map(dict_BA)
> 
>     # If the identity of the pair B, A is NaN then the pair is A, B
>     dfM.loc[dfM.idBA.isna(), "idBA"] = dfM.loc[dfM.idBA.isna(), "idAB"]
> 
>     # Map the size of the genome to the dataframe
>     dfM["lA"] = dfM['A'].map(size_dict)
>     dfM["lB"] = dfM['B'].map(size_dict)
> 
>     # Calculate the similarity
>     dfM["simAB"] = ((dfM.idAB + dfM.idBA) * 100) / (dfM.lA + dfM.lB)
> 
>     # Calculate the distance
>     dfM["distAB"] = 100 - dfM.simAB
> 
>     # Calculate the aligned fraction of the genome
>     dfM["aligned_fraction_genome_1"] = dfM.idAB / dfM.lA
>     dfM["aligned_fraction_genome_2"] = dfM.idBA / dfM.lB
>     dfM["genome_length_ratio"] = dfM[["lA", "lB"]].min(axis=1) / dfM[["lA", "lB"]].max(axis=1)
> 
>     # Calculate the similarity
>     dfM['sim'] = 100 - dfM.distAB
> 
>     # Remove the duplicate pairs
>     dfM["ordered_pair"] = dfM.apply(lambda x: str(sorted(x.pair_BA)), axis=1)
>     dfM = dfM.drop_duplicates("ordered_pair").reset_index(drop=True)
> 
>     # Remove the columns that are not needed
>     dfM = dfM.drop(columns=['identity_seq', 'pair_BA', 'idAB', 'idBA', 'lA', 'lB', 'simAB', 'ordered_pair'])
> 
>     self.dfM = dfM
> ```

The speed performance would be great, but I get different distances comparing this and the original function?

**Comment by rdenise** [comment]
I think the little difference come from how the number are handle between pure python and numpy because the calculation is exactly the same between the two functions.

But I can check that on the dataframe the number are float or int (depending of the value) that sometimes do a weird stuff when considered object

**Comment by tsp-kucbd** [comment]
Great, it works nicely!
