### ISSUE TITLE
'Killed' at 100% 

### ISSUE THREAD

**Issue by drp223** [amillard/tax_myPHAGE#4]
I've done this a few times and keep getting the same issue. This is the verbose log when running with -v flag

(base) infinite@infinite-ThinkPad-X1-Extreme:~/tax_myPHAGE$ python tax_myPHAGE.py --input '/home/infinite/Desktop/BW1.fasta'  -v flag
ic| f"Number of set threads {threads}": 'Number of set threads 8'
Found /home/infinite/tax_myPHAGE/VMR.xlsx as expected
 Found /home/infinite/tax_myPHAGE/ICTV.msh as expected
ic| f"{program_name} is installed will proceed ": 'blastdbcmd is installed will proceed '
ic| f"{program_name} is installed will proceed ": 'mash is installed will proceed '
Found /home/infinite/tax_myPHAGE/Bacteriophage_genomes.fasta as expected
Classifying:   0%|                                        | 0/1 [00:00<?, ?it/s]

Warning: Directory 'BW1_taxmyphage_results'already exists. All results will be overwritten.
ic| taxa_df:         Sort  Isolate Sort  ... Genome composition  Host source
             0          1             1  ...              dsDNA      archaea
             1          2             1  ...              dsDNA      archaea
             2          3             1  ...              dsDNA      archaea
             3          4             1  ...              dsDNA      archaea
             4          5             1  ...              dsDNA      archaea
             ...      ...           ...  ...                ...          ...
             12889  12890             1  ...              ssDNA       plants
             12890  12891             1  ...              ssDNA       plants
             12891  12892             1  ...              ssDNA       plants
             12892  12893             1  ...              dsDNA        algae
             12893  12894             1  ...              dsDNA        fungi
             
             [12894 rows x 26 columns]
ic| cmd: ('mash dist -d 0.2 -p 8 /home/infinite/tax_myPHAGE/ICTV.msh '
          'BW1_taxmyphage_results/query.fasta')

        Number of phage genomes detected with mash distance of < 0.2 is:97
The mash distances obtained for this query phage
    is a minimum value of 0.0214583 and maximum value of 0.0214583 
ic| mash_df.head(10):                        Reference  ... ANI
                      60  ./Tequatrovirus/MF327007.fna  ... NaN
                      46  ./Tequatrovirus/KY608967.fna  ... NaN
                      76  ./Tequatrovirus/MK373779.fna  ... NaN
                      45  ./Tequatrovirus/KY290975.fna  ... NaN
                      54  ./Tequatrovirus/LR215724.fna  ... NaN
                      78  ./Tequatrovirus/MK373785.fna  ... NaN
                      84  ./Tequatrovirus/MN716856.fna  ... NaN
                      69  ./Tequatrovirus/MH809535.fna  ... NaN
                      41  ./Tequatrovirus/KX130862.fna  ... NaN
                      81  ./Tequatrovirus/MK962750.fna  ... NaN
                      
                      [10 rows x 6 columns]
ic| top_50:                        Reference  ... ANI
            60  ./Tequatrovirus/MF327007.fna  ... NaN
            46  ./Tequatrovirus/KY608967.fna  ... NaN
            76  ./Tequatrovirus/MK373779.fna  ... NaN
            45  ./Tequatrovirus/KY290975.fna  ... NaN
            54  ./Tequatrovirus/LR215724.fna  ... NaN
            78  ./Tequatrovirus/MK373785.fna  ... NaN
            84  ./Tequatrovirus/MN716856.fna  ... NaN
            69  ./Tequatrovirus/MH809535.fna  ... NaN
            41  ./Tequatrovirus/KX130862.fna  ... NaN
            81  ./Tequatrovirus/MK962750.fna  ... NaN
            
            [10 rows x 6 columns]
ic| value_at_50th_position: 0.0282247
{'Tequatrovirus': 10}
ic| unique_genera: ['Tequatrovirus']
Found 1 genera associated with this query genome
ic| keys: ['KY608967',
           'KT184308',
           'AP011113',
           'JN986846',
           'MK962750',
           'MG775043',
           'HE956711',
           'KJ668714',
           'MF001360',
           'MF001359',
           'JX128259',
           'MK886800',
           'MG781190',
           'MH992510',
           'MG867727',
           'MH051915',
           'MH051916',
           'MH243439',
           'KU867876',
           'MT682712',
           'MN864145',
           'LR215722',
           'LR215724',
           'LR215723',
           'MK327942',
           'MK327939',
           'MK327946',
           'MK373779',
           'MK373787',
           'KT184311',
           'KF925357',
           'KR269718',
           'JN202312',
           'MT179807',
           'MK962757',
           'MK373781',
           'KT184312',
           'AP018932',
           'KX452698',
           'MT682714',
           'MH992121',
           'MN994497',
           'MK373785',
           'MT682713',
           'MH837626',
           'KU925172',
           'LC348379',
           'KM501444',
           'KF208315',
           'MH809535',
           'KM606994',
           'FJ839692',
           'MH553563',
           'KM607000',
           'DQ904452',
           'FJ839693',
           'MF327007',
           'MF158045',
           'MF158046',
           'MF327008',
           'MF001354',
           'KX828711',
           'KX130864',
           'HM035025',
           'KX130861',
           'KX130862',
           'LN881726',
           'LN881728',
           'LN881732',
           'MN580668',
           'LC348380',
           'AF158101',
           'AP018814',
           'MN895438',
           'MN895434',
           'MN895437',
           'KX009778',
           'HM997020',
           'KY290975',
           'MN716856',
           'MT176425',
           'MT176424',
           'MT176426']
Only found 1 genus so will proceed with getting all genomes associated with that genus
Number of known species in the genus is 83 
 
ic| f"{get_genomes_cmd=}": ("get_genomes_cmd='blastdbcmd -db "
                            '/home/infinite/tax_myPHAGE/Bacteriophage_genomes.fasta  -entry '
                            '"KY608967,KT184308,AP011113,JN986846,MK962750,MG775043,HE956711,KJ668714,MF001360,MF001359,JX128259,MK886800,MG781190,MH992510,MG867727,MH051915,MH051916,MH243439,KU867876,MT682712,MN864145,LR215722,LR215724,LR215723,MK327942,MK327939,MK327946,MK373779,MK373787,KT184311,KF925357,KR269718,JN202312,MT179807,MK962757,MK373781,KT184312,AP018932,KX452698,MT682714,MH992121,MN994497,MK373785,MT682713,MH837626,KU925172,LC348379,KM501444,KF208315,MH809535,KM606994,FJ839692,MH553563,KM607000,DQ904452,FJ839693,MF327007,MF158045,MF158046,MF327008,MF001354,KX828711,KX130864,HM035025,KX130861,KX130862,LN881726,LN881728,LN881732,MN580668,LC348380,AF158101,AP018814,MN895438,MN895434,MN895437,KX009778,HM997020,KY290975,MN716856,MT176425,MT176424,MT176426" '
                            "-out BW1_taxmyphage_results/known_taxa.fa '")
Phage is likely NOT a new species, will run further analysis now to to confirm this 
 
ic| top_df:                       Reference  ... Host source
            0  ./Tequatrovirus/MF327007.fna  ...    bacteria
            
            [1 rows x 34 columns]
ic| "Reading": 'Reading'
    self.blastn_result_file: 'BW1_taxmyphage_results/viridic_in.fa.blastn_vs2_self.tab.gz'
100%|██████████████████████████████| 1068625/1068625 [01:20<00:00, 13193.83it/s]
Killed████████████████████████████▉| 1068499/1068625 [01:20<00:00, 15073.05it/s]

**Comment by amillard** [comment]
Hi David, 

The genome is part of the Tequatrovirus , so the blast will analysis will take a while to run. But it looks like that complete ok .
I have run it with one of the genomes you provided that is also Tequatrovirus and it successfully completes 

Does it complete on any other phage you have tried or the test input we provide ? 

Can you let me know the list of out put files you get. 

you should have a list like this :

heatmap.jpg  known_taxa.fa           query.fasta       viridic_in.fa                             viridic_in.fa.ndb  viridic_in.fa.njs  viridic_in.fa.ntf
heatmap.pdf  mash.txt                similarities.tsv  viridic_in.fa.blastn_vs_self.tab          viridic_in.fa.nhr  viridic_in.fa.not  viridic_in.fa.nto
heatmap.svg  Output_of_taxonomy.csv  Summary_file.txt  viridic_in.fa.genus_species_clusters.tsv  viridic_in.fa.nin  viridic_in.fa.nsq

Can you let me know what is missing

**Comment by drp223** [comment]
This is what comes out. The summary file is empty. So far, I've not been able to successfully run it locally. They all seem to do the same thing

![image](https://github.com/amillard/tax_myPHAGE/assets/133222828/53c4044b-db94-46f7-95cc-c5b860f54aa4)

**Comment by amillard** [comment]
It looks to be failing at the post blast as you get the big blast file. 
The step where this is read into a matrix..  I am not sure why. 
Can you confirm if you run the test genome provided it works ? 
I cant repeat the error you are getting

**Comment by amillard** [comment]
Hi David, 
We think it might be failing due to the amount of memory required for that particular genus, with so many genome in it. We are trying to reduce memory consumption currently 

What is the spec of the machine you have been testing it on ? how much RAM and CPUs

Andy

**Comment by drp223** [comment]
Hi @amillard I apologize for the delay-- The test works fine for me. Only weird thing is a get a wall of text (>100 lines repeating) of: findfont: Font family 'Arial' not found.

However, eventually it ends and gives the proper test results.

As for my laptop specs: i7 8750H - 6 cores, 16gb of ram. It's rather old, but mighty for what it is. Let me know if you need more info. Thanks

**Comment by amillard** [comment]
@drp223   

If the control works, then i think it is the memory issue for that particular phages. It is in one of the biggest genera, we have tested this and @tsp-kucbd  worked out that peak memory usage is 20 GB. So this might cause the failure . We are trying to decrease memory usage to < 16Gb .  The repeating line, is just a missing font , but it still produces the output. I will put a fix to the missing font .

**Comment by amillard** [comment]
f
