### ISSUE TITLE
VMR consistency 

### ISSUE THREAD

**Issue by igortru** [amillard/tax_myPHAGE#8]
if you are going to use VMR for automatic classification you need to be sure it is internally consistent.
all cutoffs (70/95 ,genus/species) are in tact.
just run all ICTV exemplars  inside each genus separetely and calculate diameters :
interesting to know result.

especially legacy genera

**Comment by amillard** [comment]
We have, and will come as no surprise to you @igortru , that some ICTV genera are not consistent with an 70% cutoff (and some species). An message reflecting this is displayed. I am sure over time ICTV will resolve the consistency and legacy issues associated with genera. This tool might help with that ... but we cant re-define genera ... only ICTV can do that.

**Comment by amillard** [comment]
Yep aware of the process and what Andrew K has done, and continues to do. Having done this myself for the Strabo and Kyanoviriade previously,  and 500 +  phage in the last round.  But until the admin burden changes for what are simple changes based on now clear criteria, it is prohibitive to get them changed in one go by one person. Finding the inconsistencies is least of the work ..  
What I meant by "only ICTV can do that" is there is no point us creating genera/species based on 70/95 cutoffs that are only valid in our application.  ICTV taxonomy isnt perfect , but is getting better.  So will use it, and warn when there are consistencies. Far less effort for 100 people to submit 1 tax proposal than 1 person do 100 etc

**Comment by igortru** [comment]
" But until the admin burden changes"
Dear Andy!

I can suggest you small collaboration with minimal admin burden:
we need just agreement in assignment - "second opinion" rule ( I don't want do this without external confirmation from experts)
if you think that some  phage  virus names (in unclassified <taxon> bin)  can  be  moved under some ICTV species , just send pairs to viruses@ncbi.nlm.nih.gov  with subject "phage species assignment"
example:
Aeromonas phage 31.2|Biquartavirus 44RR2

**Comment by amillard** [comment]
Just to  clarify, if we find new submitted genomes that fall within current ICTV species and are in unclassified.   Just do as you suggest as above ?  is there an easy way to get all unclassified ?

**Comment by igortru** [comment]
Do you want to check all ~100k sequences with  “division Phages”   in taxonomy which have word “unclassified” inside lineages
or only genomes with word “unclassified” in lineage in your “complete genomes” list?
